### ISSUE TITLE
Layer fetch using reqwest/tokio is broken on desktop

### ISSUE THREAD

**Issue by skazemi** [frewsxcv/rgis#107]
Trying to load layers from library causes the following error:
`thread 'Async Compute Task Pool (0)' panicked at 'A Tokio 1.x context was found, but timers are disabled. Call enable_time on the runtime builder to enable timers.`

**Comment by frewsxcv** [comment]
@skazemi can you try running again? after https://github.com/frewsxcv/rgis/commit/9ff2d3b735582cede88c259bf4459c08781b7ef0

**Comment by skazemi** [comment]
@frewsxcv the issue is fixed, works as expected
