### ISSUE TITLE
Failed to run rgis in browser

### ISSUE THREAD

**Issue by piaoger** [frewsxcv/rgis#109]
I got below same error while tryhing  to run rgis.app online or local wasm build:

![image](https://user-images.githubusercontent.com/179429/209335453-70fc4140-a94a-4f2a-994c-96c9f7676c6c.png)

Edit:
To have a test by disable the system:
```rust
.with_system(handle_feature_clicked_event)
```

**Comment by frewsxcv** [comment]
Should be fixed now, thanks for the bug report
