### ISSUE TITLE
consider switching to geozero for reading

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/rgis#19]
no intermediate representation

https://github.com/pka/geozero

**Comment by pka** [comment]
Would be happy to support you! Geozero is now in a state to get feedback from the rust-geo community. Would the Discord channel be the right place for a discussion?

**Comment by frewsxcv** [comment]
hey @pka! i have a question about geozero. it's advertised as parsing without an intermediate representation, but since we're parsing into a `GeoJson` here, isn't that intermediate?

https://github.com/pka/geozero/blob/3044dfa019d45ce59f4a86acd9080f36dbafbbf3/geozero-core/src/geojson_reader.rs#L10-L12

**Comment by pka** [comment]
See https://github.com/pka/geozero/issues/1 ...

**Comment by frewsxcv** [comment]
done https://github.com/frewsxcv/rgis/commit/25ae0d7f9db420e6d858ecb571e9262ae3f58d9b https://github.com/frewsxcv/rgis/commit/d0d376551e20178eb0e548426ee8d532d7a52b2b
