### ISSUE TITLE
unable to see provided example data in rgis

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#46]
I've been so far unable to see any data in rgis.

e.g. when I run `cargo run -- sample-data/us-states.json `

rgis launches, but there is no visible layer - neither in the main canvas nor in the left panel behind the expanded layers disclosure.

<img width="1011" alt="Screen Shot 2022-02-15 at 9 45 46 AM" src="https://user-images.githubusercontent.com/217057/154119267-7a2382b0-4228-4e8f-b89b-b290127f2520.png">

I'm expecting to see the us-states rendered in the canvas and listed within the "layers" section in the left panel.

Am I missing a step?

---

Build: 5dfab4b
OS: macos 12.1
arch: aarch64

**Comment by frewsxcv** [comment]
fixed in https://github.com/frewsxcv/rgis/commit/e4fbfd4b9b495d15bea2d9fe81913dd6b31ae577
