### ISSUE TITLE
read from stdin

### ISSUE THREAD

**Issue by iwpnd** [frewsxcv/rgis#62]
Hey @frewsxcv 👋 

awesome work on the project!

Do you think it's possible to have rgis read stdin also?

something like
```
curl -s https://gist.githubusercontent.com/iwpnd/7ae8ce2f90227b0a6f51874bda0bb38b/raw/48caa3c7a379498cbe4996c5f87df4959e0c9909/test.geojson | rgis
```
would be awesome for people to quickly preview the output of an api response.

kind regards

**Comment by frewsxcv** [comment]
Thanks for the feature request! rgis can now read from stdin. Unfortunately the geojson library has a bug processing the file you shared. I opened a separate issue for that: https://github.com/georust/geojson/issues/193. I can look into it in the next day or two.

**Comment by iwpnd** [comment]
thank you @frewsxcv :)

**Comment by frewsxcv** [comment]
@iwpnd `curl -s https://gist.githubusercontent.com/iwpnd/7ae8ce2f90227b0a6f51874bda0bb38b/raw/48caa3c7a379498cbe4996c5f87df4959e0c9909/test.geojson | rgis` now works! https://github.com/frewsxcv/rgis/commit/2da38cfa27355b7f27cdfbf5246b900951e1c299 fixed it
