### ISSUE TITLE
read features and geometries

### ISSUE THREAD

**Issue by iwpnd** [frewsxcv/rgis#64]
Hi again 👋 

if i understand it correctly rgis requires input to be of type `FeatureCollection`. Given the use case #62 more often than not will I receive a single feature, that i have to put in the `features` array of a feature collection to be able to use rgis.

So this will fail if the request does not return a feature collection:

```
curl -s https://gist.githubusercontent.com/iwpnd/78c4c376addbf897453db23786bea38c/raw/6c1ce202cae8a16cb5f85367c3ba5ab328384a07/test-feature.geojson | rgis
```

Do you think it's possible to add a switch case on the `type` to let rgis do that for you?

**Comment by frewsxcv** [comment]
https://github.com/georust/geojson/issues/195

**Comment by frewsxcv** [comment]
fixed in https://github.com/frewsxcv/rgis/commit/7ad54d4813cc7adc15bc4711e806d37c7ce4c988
