### ISSUE TITLE
Zooming should consider cursor position in order to keep the feature under the cursor on the canvas

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#66]
When I want to get a closer look at a particular feature, I hover my mouse cursor over it and scroll to zoom. I'm expecting for the canvas to scale up and to keep the thing I'm interested in on the canvas.

However, with rgis it seems like zooming simply scales the canvas and the center of the canvas is not offset relative to the cursor position. This means that as the canvas zooms, the feature I'm interested in often ends up getting cropped out.

So whereas with something like google maps or openstreetmaps.org I can hover and zoom until I'm happy, instead with rgis I need to zoom, pan, zoom, pan, zoom, etc.

**Comment by frewsxcv** [comment]
Fixed in https://github.com/frewsxcv/rgis/pull/106

**Comment by michaelkirk** [comment]
The new zoom behavior feels much better! Thanks @skazemi and @frewsxcv!
