### ISSUE TITLE
zooming is very sensitive

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#67]
On my mac (MacBook Pro (14-inch, 2021)) zooming is really sensitive. It's challenging to zoom the amount I expect, and I often end of over zooming.

I'm not sure how you are interacting with scroll inputs - but I worked on a similar issue in abstreet, where we were handling winit events (are you interacting with winit or is that all abstracted behind bevy?). In winit I encountered some pretty significant differences across platform scroll behavior. IIRC some platforms report scroll events in terms of "line deltas" (coming from the old clicky scroll wheels) while others (notably mac touchpads) in terms of "pixel deltas". 

Ultimately for a decent experience I think we ended up making some guess to translate them to some common unit - like a "line" of scrolling is equal to 40px (I don't remember the exact number, but we just kind of tweaked it until it felt reasonable).

**Comment by michaelkirk** [comment]
Oh yeah! I should have mentioned that I was using web — Safari Version 15.5 (17613.2.7.1.8)

**Comment by michaelkirk** [comment]
FWIW I feel like we managed to get the scroll/zoom in abstreet behaving pretty reasonably in the browser: 

https://play.abstreet.org/dev/abstreet.html?system/us/seattle/scenarios/montlake/weekday.bin&--cam=18.19/47.64284/-122.31773

**Comment by frewsxcv** [comment]
> FWIW I feel like we managed to get the scroll/zoom in abstreet behaving pretty reasonably in the browser:
> 
> https://play.abstreet.org/dev/abstreet.html?system/us/seattle/scenarios/montlake/weekday.bin&--cam=18.19/47.64284/-122.31773

Wow this is really really smooth on the trackpad, great work. Btw at least on my cheapo mouse with a scroll wheel with discrete (not continuous) scrolling increments, it's more erratic. I wonder if there's a way we can share some of the logic here. Like a `normalize_winit_event_values` function or crate.

**Comment by michaelkirk** [comment]
I think maybe here: https://github.com/frewsxcv/rgis/blob/d558c54ff43747ce27c3e30cd574fd60f24c0129/rgis-mouse/src/lib.rs#L125

```rust
fn mouse_scroll_system(
    mut mouse_scroll_event_reader: bevy::ecs::event::EventReader<bevy::input::mouse::MouseWheel>,
    mut zoom_camera_events: bevy::ecs::event::EventWriter<rgis_events::ZoomCameraEvent>,
) {
    for event in mouse_scroll_event_reader.iter() {
        if event.y > 0. {
            zoom_camera_events.send(rgis_events::ZoomCameraEvent::zoom_in());
        } else if event.y < 0. {
            zoom_camera_events.send(rgis_events::ZoomCameraEvent::zoom_out());
        }
    }
}
```

Is it it possible to get the [units](https://docs.rs/bevy/latest/bevy/input/mouse/enum.MouseScrollUnit.html) from the scroll event? Otherwise I think you'll end up treating a change in y from a `Line` scroll the same as a `Pixel` scroll, which would be as unreasonable as interpreting kilometers as miles.

In abstreet we translated winit pixel deltas to line deltas: https://github.com/a-b-street/abstreet/blob/master/widgetry/src/event.rs#L82 and the rest of the app operates on the assumption of line deltas.

It's worth taking a look at if only to see how much I enjoy writing overly verbose code comments. 😆

**Comment by frewsxcv** [comment]
Cool! I'll try this out when I get some time. Thanks for sharing all this ⭐

**Comment by frewsxcv** [comment]
done https://github.com/frewsxcv/rgis/commit/1d210db3f0de25c93630820ee9f338d7674bb238

thanks for the suggestion!

**Comment by michaelkirk** [comment]
This feels much better for me on my mac - nice! 

But I expect that maybe you've flipped the problem so that anyone who's mouse scroll is in units of "lines" will now experience a horribly under-sensitive scroll. 

That's why in ABStreet we handled __line__ scroll different from __pixel__ scroll.

IIRC this commonly would include X11 users, and it *might* affect other platforms depending on the input device being used. e.g. I'd expect an indexed scroll wheel to return 'Lines' rather than 'Pixels' on some platforms.
