### ISSUE TITLE
Create a new layer by pasting geojson into a text field.

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#73]
Sometimes when I'm doing analysis I just want a quick way to print to stdout and view the output. Being able to copy and paste geojson into rgis to create a new layer would be a nice little quality of life thing.

I'm imagining something like: http://geojson.io/#map=2/20.0/0.0

**Comment by frewsxcv** [comment]
This is done in https://github.com/frewsxcv/rgis/commit/79ab69318206861355d379181c7d65d70cf33eab and is live on https://rgis.app/

**Comment by frewsxcv** [comment]
Although https://github.com/frewsxcv/rgis/issues/77
