### ISSUE TITLE
Loading a layer from WKT (and geojson) assumes 4326, with no way to edit it.

### ISSUE THREAD

**Issue by michaelkirk** [frewsxcv/rgis#92]
I had some WKT that I wanted to see rendered from https://github.com/georust/geo/issues/913#issuecomment-1267665597.

I saved it to a file, and loaded it in rgis (native build, not web), but I couldn't see the layer. I think this is because the import flow assumes my data is in EPSG:4326. To render, it's then projected to the rgis projection (which defaults to EPSG:3857).

I'd like to be able to declare the projection that my data has, probably as part of the load file flow.

To be clear, I don't want to **re**-project my data. I want the coordinate numbers to remain the same - I just want to declare what projection those existing numbers are from.

**Comment by frewsxcv** [comment]
@michaelkirk There is now an input field for CRS upon adding a layer. Can you test it to see if it's working for you?

**Comment by michaelkirk** [comment]
It works!
